# Demonstrate linear inverse model for the heat budget

Horizontal heat transports are non-linear terms if one assume that both temperatures and velocities have to be optimized. In order to keep the model as simple as possible, we hypothesized that only velocities require optimization. In other word, we assumed that between temperatures and circulation, the former is the best known. Doing so, heat transport terms are linear with regard to the optimization procedure.

## Inversion procedure used to optimized parameters of the model

The procedure presented here is for a linear model, the reader is referred to \citet{tarantola-1982} and \citet{mercier-1986} for further details on a non-linear formulation.

Let $\mathbf{X}=\{X^1,...,X^M\}$ refers to the finite set of $M$ parameters needed to describe the system such as velocity, fluxes or tracer concentrations. A physical model will impose $N$ constraints on the possible values of $\mathbf{X}$ which can take the functional form:
\begin{eqnarray*}
	f^1(X^1,...,X^M) &=& 0 \\
	f^2(X^1,...,X^M) &=& 0 \\
	...&& \\
	f^N(X^1,...,X^M) &=& 0
\end{eqnarray*}

Let $\mathbf{X_0}$ be an \apri state of information of the model parameters $\mathbf{X}$ and $\mathbf{E_0}$ the associated error covariance matrix. We refer to the information after inversion as the \apost or optimized state. The constraints take values $f(\mathbf{X})$ at $\mathbf{X}$ and their error covariance matrix is denoted as $\mathbf{E_c}$. The optimization procedure minimizes the following function:
\begin{equation}
	(\mathbf{X-X_0})^T \cdot \mathbf{E_0}^{-1} \cdot (\mathbf{X-X_0})
	+  f(\mathbf{X})^T \cdot \mathbf{E_c}^{-1} \cdot f(\mathbf{X}) \label{eq:costfunction}
\end{equation}
where the subscript $T$ indicates a transpose operator. The first term is the squared distance between the \apri and \apost estimates of the parameters while the second term is the constraints residual weighted by their errors. 

The best estimate $\mathbf{X^*}$ and its error covariance matrix $\mathbf{E^*}$ are given uniquely by:
    \begin{eqnarray}
        \mathbf{X^*} &=& \mathbf{X_0} - \mathbf{Q} \cdot f(\mathbf{X_0}) \label{eq:Xstar} \\
        \mathbf{E^*} &=& \mathbf{E_0} - \mathbf{Q} \cdot \mathbf{F} \cdot \mathbf{E_0} \label{eq:Estar}
    \end{eqnarray}
where $\mathbf{F}$ is the model matrix of partial derivatives (model jacobian)
    \begin{eqnarray}
        \mathbf{F}^{ij} = \frac{\partial f^i}{\partial \mathbf{X}^j}
    \end{eqnarray}
and the matrix $\mathbf{Q}$ is given by:
    \begin{eqnarray}
        \mathbf{Q} &=& \mathbf{E_0} \cdot \mathbf{F}^T \cdot \left( \mathbf{F} \cdot \mathbf{E_0} \cdot \mathbf{F}^T + \mathbf{E_c}  \right)^{-1} \label{eq:Q}
    \end{eqnarray}

## Our model

The volume conservation equation is given by the domain convergence of volume fluxes:
\begin{eqnarray}
    \nabla U^i + \nabla U_e &=& r\\
    U^i &=& U^i_g + U^i_c
\end{eqnarray}
where the $U^i$ are geostrophic volume fluxes ($m^3/s$) through each faces of the domain, $U_e$ Ekman volume fluxes and $r$ the residuals. The total geostrophic terms are decomposed into an observation-based estime $U^i_g$ and a correction term $U^i_c$ so that the first model constraint is:
\begin{eqnarray}
    \nabla U^i_c &=& r - \nabla U_e - \nabla U^i_g
\end{eqnarray}

Then for the heat budget, the domain heat content rate of change is:
\begin{eqnarray}
    \partial_t OHC + \nabla U^i \theta^i + \nabla U_e \theta_s &=& \frac{Q_{net}}{\rho_0 C_p} 
\end{eqnarray}
so that in terms of volume flux constraints it can be re-written as:
\begin{eqnarray}
     \nabla U^i_c \theta^i &=& \frac{Q_{net}}{\rho_0 C_p} - \nabla U_e \theta_s - \partial_t OHC - \nabla U^i_g \theta^i\\
\end{eqnarray}

The model is linear and simple: $f(\mathbf{X}) = \mathbf{A}\mathbf{X}$ in matrix form. When constraint should be satisfied:
\begin{eqnarray}
    \mathbf{A} \mathbf{X} &=& 0
\end{eqnarray}
with the (2,4) model matrix $\mathbf{A}$ :
\begin{eqnarray}
    \mathbf{A} &=
        \begin{pmatrix} 
            1 & -1 & -1 & 1 \\
            \theta^w & -\theta^e & -\theta^n & \theta^s 
        \end{pmatrix}
\end{eqnarray}
and the (4,1) state vector $\mathbf{X}$:
\begin{eqnarray}
    \mathbf{X} &=
        \begin{pmatrix} 
            U_c^w \\ U_c^e \\ U_c^s \\ U_c^n
        \end{pmatrix}
\end{eqnarray}
where volume fluxes are positive eastward or northward.

The model jacobian $\mathbf{F}$ is in this trivial linear case simply given by $\mathbf{A}$.
    
The a priori constraint residual is thus given by:
\begin{eqnarray}
    \mathbf{R} &=
        \begin{pmatrix} 
            r - \nabla U_e - \nabla U^i_g \\
            \frac{Q_{net}}{\rho_0 C_p} - \nabla U_e \theta_s - \partial_t OHC - \nabla U^i_g \theta^i 
        \end{pmatrix}
\end{eqnarray}

So that the a priori (and unsatisfied) model state constraints are:
\begin{eqnarray}
    \mathbf{A} \mathbf{X_0} &=& \mathbf{R}
\end{eqnarray}

Once optimised, we'll get $U^i_c$ to but this down to 0:
\begin{eqnarray}
    \mathbf{A} \mathbf{X^*} &=& 0
\end{eqnarray}
where $\mathbf{X^*}$ was given in the 1st section.    


## Matlab code
The point is to convert in python this Matlab peace of code from my toolbox and tia_nl.m:

		%-- SOLVE A LINEAR MODEL
		disp('TIA_NL MESSAGE: THIS MODEL IS LINEAR')
			
		jac = jacob(Jeval,X0,varargin{:});			
		Q   = E0 * jac' * inv(jac * E0 * jac' + Ec);
		xs  = x0 - Q*f(C,X0,varargin{:}); % Optimized parameters
		es  = diag(E0 - Q * jac * E0); % Errors
		
		Xstar = X0;
		for ix = 1 : size(Xstar,1)
			Xstar(ix,3) = {xs(ix)};
			Xstar(ix,4) = {sqrt(es(ix))};
		end%for ix
		Xstar_lin = Xstar;
		k = 1;
		
		% EVALUTE COST FUNCTION TERMS:
		cost(1,1) = (xs-x0)' * inv(E0) * (xs-x0);
		cost(1,2) = f(Meval,Xstar,varargin{:})' * inv(Ec) * f(Meval,Xstar,varargin{:});
		

In [2]:
import numpy as np

## Define problem variables

### State vector $\mathbf{X}$ and its a priori errors $\mathbf{E}_0$

Volume fluxes are in Sverdrup, positive eastward & northward


In [5]:
X = np.zeros((4,1))
# X[:,0] = [43,14,-13,18] # West, East, South, North
X[:,0] = [1,1,-1,1] # West, East, South, North
print("State vector has shape:", X.shape, "and values:") # must be 4,1
print(X)

# Set errors to a % relative value:
s = 20/100. # 20% error on all volume fluxes
E = np.zeros((4,4))
for i in range(0,4):
    E[i,i] = (s*np.abs(X[i,0]))**2 # Take the square because E is the error co-variance matrix and it scales as X^2
print("State vector co-variance error matrix has shape:", E.shape, "and values:") # must be 4,4
print(E)

State vector has shape: (4, 1) and values:
[[ 1.]
 [ 1.]
 [-1.]
 [ 1.]]
State vector co-variance error matrix has shape: (4, 4) and values:
[[0.04 0.   0.   0.  ]
 [0.   0.04 0.   0.  ]
 [0.   0.   0.04 0.  ]
 [0.   0.   0.   0.04]]


### Model matrix $\mathbf{A}$, jacobian and constraint errors $\mathbf{E}_c$

In [9]:
# Mean face temperatures:
Temp = np.zeros((4,1))
Temp[:,0] = [16.1,13.5,16.4,9.] # West, East, South, North
print("Temperature vector has shape:", Temp.shape, "and values:") # must be 4,1
print(Temp)

Temperature vector has shape: (4, 1) and values:
[[16.1]
 [13.5]
 [16.4]
 [ 9. ]]


In [10]:
# Model matrix:
A = np.zeros((2,4))
A[0,:] = [1,-1,-1,1] # Volume constraint (Sv)
A[1,:] = np.diag(Temp*np.array(([1,-1,-1,1]))) # Heat constraint (Sv*degC)
print("Model matrix A has shape:", A.shape, "and values:") # must be 2,4
print(A)

Model matrix A has shape: (2, 4) and values:
[[  1.   -1.   -1.    1. ]
 [ 16.1 -13.5 -16.4   9. ]]


In [31]:
# A priori constraint residuals:
print("A priori constraint residuals:\n", A.dot(X))

# Constraint errors:
Ec = np.zeros((2,2))
Ec[0,0] = 1**2 # Volume constraint residual squared error in [Sv]^2
Ec[1,1] = 10**2 # Heat constraint residual  squared error in [Sv*degC]^2
print("Constraints error co-variance matrix has shape:", Ec.shape, "and values:") # must be 2,2
print(Ec)

A priori constraint residuals:
 [[ 2.]
 [28.]]
Constraints error co-variance matrix has shape: (2, 2) and values:
[[  1.   0.]
 [  0. 100.]]


## Solve the inverse problem

In [32]:
# Put solver into a function
def tia_lin(X0,E0,Ec,A):
    # Solve:
    J = A # The model jacobian is A in the linear case
    Q = (E0.dot(J.T)).dot( np.linalg.inv((J.dot(E0)).dot(J.T) + Ec) )
    # Final state:
    Xs = X0 - Q.dot(A.dot(X0))
    Es = E0 - (Q.dot(J)).dot(E0)
    return Xs,Es

# Solve it:
X0 = X
E0 = E
Xs, Es = tia_lin(X0,E0,Ec,A)

## Compare a priori with optimised state

In [26]:
# State vectors:
print("Initial state vector:\n",X0.T)
print("Optimised state vector:\n",Xs.T)

Initial state vector:
 [[ 1.  1. -1.  1.]]
Optimised state vector:
 [[ 0.82315573  1.15709661 -0.82087716  0.87708201]]


In [27]:
# State vectors error:
print("Initial state vector errors:\n",np.sqrt(np.diag(E0)))
print("Optimised state vector errors:\n",np.sqrt(np.diag(Es)))

Initial state vector errors:
 [0.2 0.2 0.2 0.2]
Optimised state vector errors:
 [0.18997044 0.19217409 0.18968574 0.19490357]


In [28]:
# Constraint residuals:
print("A priori constraint residuals:\n", A.dot(X0))
print("Optimised constraint residuals:\n",A.dot(Xs))

A priori constraint residuals:
 [[ 2.]
 [28.]]
Optimised constraint residuals:
 [[ 1.36401829]
 [18.98812652]]
